spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/plansdb
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: 'ant-path-matcher'

plan-api:
 messages:
  planSaveSucc: Plan Save Successfull..
  planSaveFail: Plan Save Fail..
  planUpdateSucc: Plan Update Successfull..
  planUpdateFail: Plan Update Fail..
  planDeleteSucc: Plan Delete Successfully..
  planDeleteFail: Plan Delete Fail..
  planStatusChange: Plan Status Change Successfully..
  planStatusChangeFail: Plan Status Change Fail..
        